//! The RRSIG record data type.

#[cfg(feature = "std")]
use core::cmp::Ordering;
use domain_macros::*;

use crate::new::base::build::BuildInMessage;
use crate::new::base::name::{CanonicalName, Name, NameCompressor};
use crate::new::base::wire::{AsBytes, BuildBytes, TruncationError, U16};
use crate::new::base::{CanonicalRecordData, RType, TTL, Timestamp};

use super::SecAlg;

//----------- Rrsig ----------------------------------------------------------
/// A cryptographic signature on a DNS Resource Record Set.
///
/// The purpose of an [`Rrsig`] record is to serve signatures for the
/// corresponding Resource Record Set (RRset). An RRset is a collection of all
/// records with the same `owner name`, [`RType`] and [`RClass`] (e.g. all
/// `MX` records in the `IN` class for `example.com.`).
///
/// The query response for a signed zone includes the requested RRset and the
/// signature associated to prove the validity of the data. The [`Rrsig`]
/// record is always next to the data its signature it contains. If the RRset
/// is part of the `Answer` section then the [`Rrsig`] record is also part of
/// the `Answer` section, the same applies to records in the `Authority` or
/// `Additional` section.
///
/// The signature is computed with a cryptographic key pair. The public part
/// of that key is stored in the [`DNSKey`] record.
///
/// [`Rrsig`] is specified by [RFC 4034, section 3].
///
/// ## Wire format
///
/// The memory layout of the [`Rrsig`] type is identical to its serialization
/// in the wire format. This means that it can be parsed from the wire format
/// in a zero-copy fashion, avoiding a copy of the key material.
///
/// ## Usage
///
/// Because [`DNSKey`] is a record data type, it is usually handled within an
/// enum like [`RecordData`]. This section describes how to use it
/// independently.
///
///
/// ```
/// # use domain::new::base::wire::{ParseBytes, U16};
/// # use domain::new::rdata::{Rrsig, SecAlg};
/// # use domain::new::base::{Serial, TTL, RType};
/// # use domain::new::base::name::NameBuf;
/// #
/// let bytes = b"\
///     \x00\x01\
///     \x0D\
///     \x02\
///     \x00\x00\x0E\x10\
///     \x67\x5B\xB6\xC6\
///     \x67\x4C\x74\x86\
///     \x05\xE3\
///     \x07example\x03com\x00\
///     \x00\x00\x00\x00\x00\x00\x00\x00";
///
/// // Parse the record data from the wire format.
/// let rrsig_bytes = Rrsig::parse_bytes(bytes).unwrap();
///
/// //--- Construct the `Rrsig` structure manually.
///
/// let name: NameBuf = "example.com.".parse::<NameBuf>().unwrap();
/// // The signature is zeroed out and is just for illustration purposes.
/// let bytes = [0, 0, 0, 0, 0, 0, 0, 0];
///
/// let rrsig_manual = Rrsig {
///     // This signature covers the resource record set for `A` records.
///     rtype: RType::A,
///     // The signature used the ECDSA Curve P-256 with SHA-256 algorithm.
///     algorithm: SecAlg { code: 13 },
///     labels: 2,
///     ttl: TTL::from(3600), // one hour
///     // The signature expires on Friday, December 13, 2024 at 4:23:34 AM.
///     expiration: Serial::new(1734063814),
///     // The signatures validity started on Sunday, December 1, 2024 at 2:36:54 PM.
///     inception: Serial::new(1733063814),
///     // The signature is generated by the `DNSKey` with the key tag 1507.
///     keytag: U16::new(1507),
///     signer: &name,
///     signature: &bytes,
/// };
///
/// // Verify that the `Rrsig` records are equal.
/// assert_eq!(rrsig_bytes, rrsig_manual);
/// ```
///
/// [`DNSKey`]: super::DNSKey
/// [`RClass`]: crate::new::base::RClass
/// [`RecordData`]: crate::new::rdata::RecordData
/// [RFC 4034, section 3]: https://datatracker.ietf.org/doc/html/rfc4034#section-3
#[derive(Clone, Debug, PartialEq, Eq, Hash, BuildBytes, ParseBytes)]
pub struct Rrsig<'a> {
    /// The type of the RRset being signed.
    pub rtype: RType,

    /// The cryptographic algorithm used to construct the signature.
    pub algorithm: SecAlg,

    /// The number of labels in the signed RRset's owner name.
    ///
    /// This number is used in the DNSSEC validation process to differentiate
    /// between regular and wildcard synthesised [`Rrsig`] records.
    ///
    /// The [`Rrsig`] record originates in a wildcard if this number is
    /// smaller than the number of labels in the owner name. With this number
    /// the original wildcard record can be reconstructed to verify the
    /// signature.
    pub labels: u8,

    /// The (original) TTL of the signed RRset.
    ///
    /// All TTL values of an RRset are expected to have the same value (see
    /// [section 5.2 of RFC2181]). The [`Rrsig`] record matches this value.
    ///
    /// *Note: The [`Rrsig`] record is the exception to this rule of identical
    /// TTL values (see [section 3 of RFC4034]). There may be [`Rrsig`]
    /// records under the same `owner name` but with different TTL values.*
    ///
    /// [section 5.2 of RFC2181]: https://datatracker.ietf.org/doc/html/rfc2181#section-5.2
    /// [section 3 of RFC4034]: https://datatracker.ietf.org/doc/html/rfc4034#section-3
    pub ttl: TTL,

    /// The point in time at which the signature expires.
    pub expiration: Timestamp,

    /// The point in time at which the signature was created.
    pub inception: Timestamp,

    /// The key tag of the [`DNSKey`] used to make the signature.
    ///
    /// The key tag is computed from a [`DNSKey`] record. This value might not
    /// be unique among all [`DNSKey`] records present in a zone.
    ///
    /// [`DNSKey`]: super::DNSKey
    pub keytag: U16,

    /// The name identifying the signer.
    ///
    /// This name points to the zone which contains the [`DNSKey`] records
    /// used to verify the signature.
    ///
    /// [`DNSKey`]: super::DNSKey
    pub signer: &'a Name,

    /// The serialized cryptographic signature.
    pub signature: &'a [u8],
}

//--- Interaction

impl Rrsig<'_> {
    /// Copy referenced data into the given [`Bump`](bumpalo::Bump) allocator.
    #[cfg(feature = "bumpalo")]
    pub fn clone_to_bump<'r>(&self, bump: &'r bumpalo::Bump) -> Rrsig<'r> {
        use crate::utils::dst::copy_to_bump;

        Rrsig {
            signer: copy_to_bump(self.signer, bump),
            signature: bump.alloc_slice_copy(self.signature),
            ..self.clone()
        }
    }

    /// new
    pub fn notnew() {}
}

//--- Canonical operations

impl CanonicalRecordData for Rrsig<'_> {
    fn cmp_canonical(&self, that: &Self) -> Ordering {
        let this_initial = (
            self.rtype,
            self.algorithm,
            self.labels,
            self.ttl,
            self.expiration.as_bytes(),
            self.inception.as_bytes(),
            self.keytag,
        );
        let that_initial = (
            that.rtype,
            that.algorithm,
            that.labels,
            that.ttl,
            that.expiration.as_bytes(),
            that.inception.as_bytes(),
            that.keytag,
        );
        this_initial
            .cmp(&that_initial)
            .then_with(|| self.signer.cmp_lowercase_composed(that.signer))
            .then_with(|| self.signature.cmp(that.signature))
    }
}

//--- Building in DNS messages

impl BuildInMessage for Rrsig<'_> {
    fn build_in_message(
        &self,
        contents: &mut [u8],
        start: usize,
        _compressor: &mut NameCompressor,
    ) -> Result<usize, TruncationError> {
        let bytes = contents.get_mut(start..).ok_or(TruncationError)?;
        let rest = self.build_bytes(bytes)?.len();
        Ok(contents.len() - rest)
    }
}

//
// --- Functions to make it easier to transition for old base.
// These functions should be marked as deprecated when most the initial
// migration to new base has completed.
impl Rrsig<'_> {
    /// Return the RRtype that the signature covers.
    pub fn type_covered(&self) -> RType {
        self.rtype
    }

    /// Return the original TTL of signed RRset.
    pub fn original_ttl(&self) -> TTL {
        self.ttl
    }

    /// Return the key tag of the key that created the signature.
    pub fn key_tag(&self) -> u16 {
        self.keytag.into()
    }

    /// Return the expiration time of the signature.
    pub fn expiration(&self) -> Timestamp {
        self.expiration
    }
}
