//! Macro rules uses in `domain::new`.

/// Define known DNS constants with an associated name and value.
///
/// The constants are defined on top of an existing struct. The macro defines
/// two lists `$values` & `$names`. The visibility of both lists can be
/// defined. These lists are used to implement two basic methods for the
/// struct automatically:
///
/// - `get_mnemonic()`
/// - `from_mnemonic()`
///
/// The visibility of the above functions is the same as the visibility of the
/// `$names` list. If the `$names` list doesn't contain mnemonics the
/// functions serve no purpose and should be hidden to avoid confusion.
macro_rules! known_values_define {
    (
        $(#[$type_attr:meta])*
        $type:ident:: (
            $values_vis:vis $values:ident ,
            $names_vis:vis $names:ident
        ) = [ $(
            $(#[$value_attr:meta])*
            $value_name:literal as $value_constant:ident = $value:expr,
        )* ];
    ) => {
        $(#[$type_attr])*
        /// This implementation block contains all constant values.
        impl $type {
            $(
                $(#[$value_attr])*
                pub const $value_constant: $type = $value;
            )*
        }

        // This block writes the list called $values. Containing all defined
        // values.
        $(#[$type_attr])*
        impl $type {
            /// The
            #[doc = concat!("[`", stringify!($type), "::", stringify!($values), "`]")]
            /// list contains all constant values associated to the type.
            ///
            /// *This list is autogenerated through macro invocation.*
            $values_vis const $values: &'static [$type] = &[
                $($value,)*
            ];

            /// The
            #[doc = concat!("[`", stringify!($type), "::", stringify!($names), "`]")]
            /// list contains all names/mnemonics associated to the type. The
            /// position of any name in this list correlates with the position
            /// of the value in
            #[doc = concat!("[`", stringify!($type), "::", stringify!($values), "`].")]
            ///
            /// *For constants that do not contain defined mnemonics this list
            /// is hidden.*
            ///
            /// *This list is autogenerated through macro invocation.*
            $names_vis const $names: &'static [&'static str] = &[
                $(
                    $value_name ,
                )*
            ];

            /// Mnemonic representation of `self` if it's defined.
            ///
            /// *For constants that don't have defined mnemonics this function
            /// is hidden.*
            ///
            /// *This function is autogenerated through macro invocation.*
            #[must_use]
            $names_vis fn get_mnemonic(&self) -> Option<&'static str> {
                if let Some(pos) =
                    Self::$values.iter().position(|t| t == self)
                {
                    return Self::$names.get(pos).map(|s| *s);
                };
                None
            }

            /// Associated constant value of
            #[doc = concat!("[`", stringify!($type), "`]")]
            /// if `mnemonic` is recognised.
            ///
            /// *For constants that don't have defined mnemonics this function
            /// is hidden.*
            ///
            /// *This function is autogenerated through macro invocation.*
            #[must_use]
            // For functions that do not have defined mnemonics this function
            // is hidden and possibly unused.
            #[allow(unused)]
            $names_vis fn from_mnemonic(mnemonic: &str) -> Option<Self> {
                if let Some(pos) = Self::$names
                    .iter()
                    .position(|s| mnemonic.eq_ignore_ascii_case(s))
                {
                    return Self::$values.get(pos).map(|s| *s);
                };
                None
            }
        }
    };
}

/// From implementations for DNS constants.
///
/// This macro implements conversions from the primitive type into the wrapper
/// type and vice versa.
///
/// The macro requires the struct to have a `code` field containing the
/// associated value with a From conversion into the primitive type, if
/// needed. And a `new()` method which takes the primitive type and converts
/// it into the struct.
///
/// The following implementations result from this macro:
///
/// - fn from(value: $value_type) -> $type
/// - fn from(value: $type) -> $value_type
macro_rules! known_values_from_and_to_primitive {
    ($type:ident, $value_type:ident) => {
        //--- Conversion to and from primitive
        impl From<$value_type> for $type {
            fn from(value: $value_type) -> Self {
                Self::new(value)
            }
        }

        impl From<$type> for $value_type {
            fn from(value: $type) -> Self {
                value.code.into()
            }
        }
    };
}
