[package]
name = "domain-macros"

# Copied from 'domain'.
version = "0.10.3"
rust-version = "1.68.2"
edition = "2021"

authors = ["NLnet Labs <dns-team@nlnetlabs.nl>"]
description = "Procedural macros for the `domain` crate."
documentation = "https://docs.rs/domain-macros"
homepage = "https://github.com/nlnetlabs/domain/"
repository = "https://github.com/nlnetlabs/domain/"
keywords = ["DNS", "domain"]
license = "BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
